services:
    Ibexa\FieldTypeRichText\FieldType\RichText\SearchField:
        arguments:
            $shortTextExtractor: '@Ibexa\FieldTypeRichText\RichText\TextExtractor\ShortTextExtractor'
            $fullTextExtractor: '@Ibexa\FieldTypeRichText\RichText\TextExtractor\FullTextExtractor'
        tags:
            - {name: ibexa.field_type.indexable, alias: ezrichtext}
