services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ibexa\Contracts\FieldTypeRichText\Configuration\ProviderService:
        alias: Ibexa\FieldTypeRichText\Configuration\AggregateProvider
