imports:
    - { resource: ui/mappers.yaml }

parameters:
    # set via compiler pass
    ezplatform.ezrichtext.alloy_editor: []

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\FieldTypeRichText\Configuration\Provider\CustomStyle:
        arguments:
            $customStyleConfigurationMapper: '@Ibexa\FieldTypeRichText\Configuration\UI\Mapper\CustomStyle'

    Ibexa\FieldTypeRichText\Configuration\Provider\CustomTag:
        arguments:
            $customTagConfigurationMapper: '@Ibexa\FieldTypeRichText\Configuration\UI\Mapper\CustomTag'

    Ibexa\FieldTypeRichText\Configuration\Provider\AlloyEditor:
        arguments:
            $alloyEditorConfiguration: '%ezplatform.ezrichtext.alloy_editor%'

    Ibexa\FieldTypeRichText\Configuration\Provider\CKEditor:
        arguments:
            $customStylesConfiguration: '%ezplatform.ezrichtext.custom_styles%'

    Ibexa\FieldTypeRichText\Configuration\AggregateProvider:
        arguments:
            $providers: !tagged ibexa.field_type.richtext.configuration.provider
