services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ibexa\Bundle\FieldTypeRichText\Controller\RichTextConfigController:
        tags:
            - controller.service_arguments
