parameters:
    # Rich Text Custom Tags global configuration
    ibexa.field_type.richtext.custom_tags: {}

    # Rich Text Custom Tags default scope (for SiteAccess) configuration
    ibexa.site_access.config.default.fieldtypes.ezrichtext.custom_tags: []

    # Rich Text Custom Styles global configuration
    ibexa.field_type.richtext.custom_styles: {}
    # Rich Text Custom Styles default scope (for SiteAccess) configuration
    ibexa.site_access.config.default.fieldtypes.ezrichtext.custom_styles: []

    # FieldType settings
    # Default XSL stylesheets for RichText rendering to HTML5.
    # Built-in stylesheets are treated as custom for the sake of extensibility.
    ibexa.site_access.config.default.fieldtypes.ezrichtext.output_custom_xsl:
        -
            path: '%kernel.project_dir%/vendor/ibexa/fieldtype-richtext/src/bundle/Resources/richtext/stylesheets/docbook/xhtml5/output/core.xsl'
            priority: 0

    ibexa.site_access.config.default.fieldtypes.ezrichtext.edit_custom_xsl:
        -
            path: '%kernel.project_dir%/vendor/ibexa/fieldtype-richtext/src/bundle/Resources/richtext/stylesheets/docbook/xhtml5/edit/core.xsl'
            priority: 0

    ibexa.site_access.config.default.fieldtypes.ezrichtext.input_custom_xsl: []

    # RichText field type template tag settings
    # 'default' and 'default_inline' tag identifiers are reserved for fallback
    ibexa.site_access.config.default.fieldtypes.ezrichtext.tags.default:
        template: '@@IbexaFieldTypeRichText/RichText/tag/default.html.twig'
    ibexa.site_access.config.default.fieldtypes.ezrichtext.tags.default_inline:
        template: '@@IbexaFieldTypeRichText/RichText/tag/default_inline.html.twig'

    # RichText field type template style settings
    # 'default' and 'default_inline' tag identifiers are reserved for fallback
    ibexa.site_access.config.default.fieldtypes.ezrichtext.styles.default:
        template: '@@IbexaFieldTypeRichText/RichText/style/default.html.twig'
    ibexa.site_access.config.default.fieldtypes.ezrichtext.styles.default_inline:
        template: '@@IbexaFieldTypeRichText/RichText/style/default_inline.html.twig'

    # RichText field type embed settings
    ibexa.site_access.config.default.fieldtypes.ezrichtext.embed.content:
        template: '@@IbexaFieldTypeRichText/RichText/embed/content.html.twig'
    ibexa.site_access.config.default.fieldtypes.ezrichtext.embed.content_denied:
        template: '@@IbexaFieldTypeRichText/RichText/embed/content_denied.html.twig'
    ibexa.site_access.config.default.fieldtypes.ezrichtext.embed.content_inline:
        template: '@@IbexaFieldTypeRichText/RichText/embed/content_inline.html.twig'
    ibexa.site_access.config.default.fieldtypes.ezrichtext.embed.content_inline_denied:
        template: '@@IbexaFieldTypeRichText/RichText/embed/content_inline_denied.html.twig'
    ibexa.site_access.config.default.fieldtypes.ezrichtext.embed.location:
        template: '@@IbexaFieldTypeRichText/RichText/embed/location.html.twig'
    ibexa.site_access.config.default.fieldtypes.ezrichtext.embed.location_denied:
        template: '@@IbexaFieldTypeRichText/RichText/embed/location_denied.html.twig'
    ibexa.site_access.config.default.fieldtypes.ezrichtext.embed.location_inline:
        template: '@@IbexaFieldTypeRichText/RichText/embed/location_inline.html.twig'
    ibexa.site_access.config.default.fieldtypes.ezrichtext.embed.location_inline_denied:
        template: '@@IbexaFieldTypeRichText/RichText/embed/location_inline_denied.html.twig'

    # RichText namespaces map to migrate
    ibexa.field_type.rich_text.namespaces_migration_map:
        'xmlns:ezxhtml="http://ez.no/xmlns/ezpublish/docbook/xhtml"': 'xmlns:ezxhtml="http://ibexa.co/xmlns/dxp/docbook/xhtml"'
        'xmlns:ezcustom="http://ez.no/xmlns/ezpublish/docbook/custom"': 'xmlns:ezcustom="http://ibexa.co/xmlns/dxp/docbook/custom"'
        'ezxhtml:class="ez-embed-type-image"': 'ezxhtml:class="ibexa-embed-type-image"'
        'xmlns:ez="http://ez.no/xmlns/ezpublish/docbook"': 'xmlns:ez="http://ibexa.co/xmlns/dxp/docbook"'
        'xmlns:a="http://ez.no/xmlns/annotation"': 'xmlns:a="http://ibexa.co/xmlns/annotation"'
        'xmlns:m="http://ez.no/xmlns/module"': 'xmlns:m="http://ibexa.co/xmlns/module"'
