ibexa.rest.richtext_config:
    path: /richtext-config
    controller: 'Ibexa\Bundle\FieldTypeRichText\Controller\RichTextConfigController::loadConfigAction'
    methods: [GET]
    options:
        expose: true
