services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\FieldTypeRichText\Translation\Extractor\OnlineEditorCustomAttributesExtractor:
        arguments:
            $siteAccessList: '%ibexa.site_access.list%'
        tags:
            - { name: jms_translation.extractor, alias: ez_online_editor_attributes }
