services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ibexa\FieldTypeRichText\FieldType\RichText\RichTextStorage\Gateway\DoctrineStorage:
        arguments:
            - '@Ibexa\Core\FieldType\Url\UrlStorage\Gateway\DoctrineStorage'
            - '@ibexa.api.storage_engine.legacy.connection'
