parameters:
    ezrichtext.custom_tags.translation_domain: 'custom_tags'
    ezrichtext.custom_styles.translation_domain: 'custom_styles'
    ezrichtext.online_editor.translation_domain: 'online_editor'

services:
    _defaults:
        autowire: true
        public: false

    # RichText Custom Tags UI config attribute type mappers
    Ibexa\FieldTypeRichText\Configuration\UI\Mapper\CustomTag\CommonAttributeMapper:
        tags:
            - { name: ibexa.field_type.richtext.configuration.custom_tag.mapper, priority: 0 }

    Ibexa\FieldTypeRichText\Configuration\UI\Mapper\CustomTag\ChoiceAttributeMapper:
        parent: Ibexa\FieldTypeRichText\Configuration\UI\Mapper\CustomTag\CommonAttributeMapper
        autowire: true
        public: false
        tags:
            - { name: ibexa.field_type.richtext.configuration.custom_tag.mapper, priority: 10 }

    # RichText Custom Tags UI config mapper
    Ibexa\FieldTypeRichText\Configuration\UI\Mapper\CustomTag:
        arguments:
            $customTagsConfiguration: '%ezplatform.ezrichtext.custom_tags%'
            $translatorBag: '@translator'
            $translationDomain: '%ezrichtext.custom_tags.translation_domain%'
            $customTagAttributeMappers: !tagged ibexa.field_type.richtext.configuration.custom_tag.mapper

    # RichText Custom Styles UI config mapper
    Ibexa\FieldTypeRichText\Configuration\UI\Mapper\CustomStyle:
        arguments:
            $customStylesConfiguration: '%ezplatform.ezrichtext.custom_styles%'
            $translationDomain: '%ezrichtext.custom_styles.translation_domain%'

    Ibexa\FieldTypeRichText\Configuration\UI\Mapper\OnlineEditorConfigMapper:
        alias: Ibexa\FieldTypeRichText\Configuration\UI\Mapper\OnlineEditor

    Ibexa\FieldTypeRichText\Configuration\UI\Mapper\OnlineEditor:
        arguments:
            $translationDomain: '%ezrichtext.online_editor.translation_domain%'
